### ISSUE TITLE
土日の対応

### ISSUE THREAD

**Issue by ino256** [osamutake/japanese-holidays-js#2]
とても重宝しています、ありがとうございます。

`isHoliday` というメソッド名から、土日にも対応してほしいなと思っております。第3引数を、土日を含めるかどうかのオプションとして使用するのはいかがでしょうか。

``` coffee
JapaneseHolidays.isHoliday(date, furikae = true, isIncludedSatAndSun = true)
```

**Comment by osamutake** [comment]
確かに Holiday を祝祭日、ではなく休日、あるいは休業日、という意味に読んだ場合には、土日を含めるという需要もありそうですね。

土曜日は含めず日曜日のみが欲しい場合も考えると

``` javascript
JapaneseHolidays.isHoliday(date, includeFurikae = true, 
                           includeSunday = false, includeSaturday = false)
```

でしょうか。

日曜日や土曜日に祝日が重なる場合の戻り値は、休業日である理由を答えるという考え方であれば祝日名ではなく曜日とするのが良いのでしょうか？それとも祝日名を返した方が？？？ちょっと迷います。

また、ここに土日を入れてしまうと `getHolidaysOf` との整合性が取れなくなるのが気になります。
`getHolidaysOf` が土日を返すのは、さすがにあまり需要がなさそう。年間の休業日数を知りたい場合とか？でもそれなら夏季休業とか冬季休業とかもありそうですし・・・

業種によっては火曜日休みなどもありそうですし・・・

などと考えると、本当にライブラリに含めたほうが良いのか、それとも

``` javascript
var holiday = theDay.getDay() == 0 ? '日曜日' :
              theDay.getDay() == 6 ? '土曜日' : JapaneseHolidays.isHoliday(theDay);
```

のようにライブラリ外でその都度、アプリケーション側で対応したほうがいいのか、わからなくなってきました。

うーむ、どうでしょうね。

**Comment by ino256** [comment]
なるほど、難しいですね。
曜日判定を別で行うのが冗長に感じたので提案させていただきましたが、“一般的な休日”を含めるのかはちょっと考える必要がありそう…。

一旦クローズしておきます。ご検討ありがとうございます！
