### ISSUE TITLE
2019年祝日対応について

### ISSUE THREAD

**Issue by sbs-nakajima** [osamutake/japanese-holidays-js#4]
こんにちは。重宝させていただいております。

2019年の天皇退位・即位に伴う祝日の変更・追加について、
ご対応予定はございますでしょうか？
ご検討頂けますと幸いです。

**Comment by osamutake** [comment]
リマインドありがとうございます。報道を見る限り、

* 12/23 の天皇誕生日 = 2018年までで終了
* 5/1 が名前未定の祝日 = 2019 年のみ
* 10/22 が即位礼正殿の儀 = 2019 年のみ
* 2/23 の天皇誕生日 = 2020年から開始

ということになりそうでしょうか。

2019/5/1 の祝日の名称が決まったら反映しようと思います。

私が気づいていなさそうでしたら、もう一度リマインドするか、あるいはプルリクエストを送ってみるなどしていただけると大変助かります。

**Comment by sbs-nakajima** [comment]
お早い返信感謝します。
では、2019/5/1 の祝日の名称が決定しましたらまたコメントさせていただきます。
よろしくお願いいたします。

**Comment by osamutake** [comment]
[v1.0.7](https://github.com/osamutake/japanese-holidays-js/releases/tag/v1.0.7) にて対応しました。
ご指摘＆プルリクありがとうございました。
