### ISSUE TITLE
japanese-holidays.min.js だと "ReferenceError: JapaneseHolidays is not defined" 

### ISSUE THREAD

**Issue by yasuoka** [osamutake/japanese-holidays-js#7]
japanese-holidays.min.js を読み込んで、`JapaneseHolidays.getHolidaysOf(2020)` などとすると、`"ReferenceError: JapaneseHolidays is not defined"` となります。
* リビルドはせず、git に commit されている .js で試行
*  minify されてない japanese-holidays.js であれば問題なし
*  v1.0.6 では問題なく、v1.0.7、v1.0.8 で発生
* 実行環境は、chromium-76.0.3809.100 と firefox-66.0.2 で発生

**Comment by osamutake** [comment]
ご指摘ありがとうございます。
おっしゃるとおりの問題を確認いたしました。minify 時にごっそり変数名が失われているようです。
これはひどい。

https://github.com/osamutake/japanese-holidays-js/blob/master/Makefile#L14

ここがまずい気がします。確認できたら修正版をリリースいたします。

**Comment by osamutake** [comment]
直ったと思います。どうぞ御利用下さい。

**Comment by yasuoka** [comment]
修正されていることを確認しました。 迅速な修正ありがとうございました！

**Comment by tokuchi0823** [comment]
お世話になっております。

すいません、v1.0.10についても現在もこちらの事象再発していないでしょうか？
同様にv1.0.9 では問題なくv1.0.10では`"ReferenceError: JapaneseHolidays is not defined"`
が発生します。

おそらく本日から？のようです。

**Comment by yasuoka** [comment]
@tokuchi0823 さん、

> すいません、v1.0.10についても現在もこちらの事象再発していないでしょうか？ 同様にv1.0.9 では問題なくv1.0.10では`"ReferenceError: JapaneseHolidays is not defined"` が発生します。

Git にコミットされたものを確認しましたが、再現しないです。使われている japanese-holidays.min.js が壊れてるとかないでしょうか? 以下のコマンドのいずれかで、結果が一致するかでこわれていないかを確認できます。

```
$ git hash-object lib/japanese-holidays.min.js
8a1b5f7803a80ce7b89cf7bf9ca6105f1df68382
$
$ sha256 lib/japanese-holidays.min.js
SHA256 (lib/japanese-holidays.min.js) = fe42ecec0eacf73586bbb3ff98ae981f3f30365e24bb7659bcd1d3ece383e15e
$
```

**Comment by tokuchi0823** [comment]
@yasuoka 
回答ありがとうございます！
私の方では、CDNでこちらを利用させていただいているのですが、
どうやらそちらがおかしいようです。

すでにyasuoka 様の方でPRあげられている通り、
rawgitの終了が原因そうですね。。
