### ISSUE TITLE
2021年祝日対応について

### ISSUE THREAD

**Issue by mpg-hayasaki** [osamutake/japanese-holidays-js#8]
こんにちは

2021年のオリンピック開催に伴う祝日の変更・追加について、対応予定はございますでしょうか？
法律も改正されているようですので、ご検討頂けますと幸いです。

https://www8.cao.go.jp/chosei/shukujitsu/gaiyou.html
令和３年（2021年）に限り、「海の日」は7月22日に、「スポーツの日」は7月23日に、「山の日」は8月8日(※）になります。

**Comment by osamutake** [comment]
長いこと対応しておらずすみませんでした。
ご指摘および PL 大変ありがとうございました。
